KS3-3 Multiplication table
Alex43063/kotlinSprint pull request #15
Opened 2024-09-19 08:42 UTC by Alex43063

2024-09-19 14:02 UTC, ievetrovdev requested changes
По оформлению пулл реквеста:
 - Префикс проекта с названием и номером урока задачи следует прописывать в названии пулл реквеста. Например, "KS-1-1 сделал то-то".
 В рабочем процессе важно сохранять стиль офрмления ПР, по ним работаеют смежные программы. И если ты делаешь ошибку может поломаться рабочий процесс. Так что соблюдай стиль полностью

2024-09-19 14:02 UTC, ievetrovdev commented on src/main/kotlin/Lesson3-3.kt
> +        println("$numForMultiplication x $i = ${numForMultiplication * i}")
В твоем решении функция println() вызывается 9 раз, поскольку она вызывается внутри цикла for, который выполняется 9 раз. Чтобы соответствовать условию задачи, необходимо, чтобы вся таблица умножения была напечатана с использованием одной функции println().
Тут лучше будет использовать [raw-строки](https://kotlinlang.org/docs/strings.html#raw-strings)

2024-09-19 16:48 UTC, Alex43063 commented on src/main/kotlin/Lesson3-3.kt
> +        println("$numForMultiplication x $i = ${numForMultiplication * i}")
Исправил

2024-09-20 07:13 UTC, ievetrovdev approved these changes

2024-09-20 14:39 UTC, merged