KS3-5 Parsing info string about step in chess from server
Alex43063/kotlinSprint pull request #17
Opened 2024-09-19 09:21 UTC by Alex43063

2024-09-19 14:03 UTC, ievetrovdev requested changes

2024-09-19 14:03 UTC, ievetrovdev commented on src/main/kotlin/Lesson3-5.kt
> +    val infoAboutStepList = infoAboutStepString.split(";")
Мы пользуемся сплит и обрати внимание на его сигнатуру. метод имеет ключевое слово vararg - то есть он может принимать произвольное количество параметров. то есть в данном случае разделителей. Подробнее тут https://metanit.com/kotlin/tutorial/3.2.php

2024-09-19 16:52 UTC, Alex43063 commented on src/main/kotlin/Lesson3-5.kt
> +    val infoAboutStepList = infoAboutStepString.split(";")
исправил

2024-09-20 07:13 UTC, ievetrovdev approved these changes

2024-09-20 14:40 UTC, merged