KS-4-3 Calculate conditions for grow up beans
Alex43063/kotlinSprint pull request #20
Opened 2024-09-21 12:41 UTC by Alex43063

2024-09-21 19:21 UTC, ievetrovdev requested changes

2024-09-21 19:21 UTC, ievetrovdev commented on src/main/kotlin/Lesson4-3.kt
> +const val GOOD_CONDITIONS_IS_SUNNY_DAY = true
Здесь тоже лучше использовать более подходящее название для boolean, начиная с IS

2024-09-22 06:44 UTC, Alex43063 commented on src/main/kotlin/Lesson4-3.kt
> +const val GOOD_CONDITIONS_IS_SUNNY_DAY = true
Исправил

2024-09-22 18:56 UTC, ievetrovdev approved these changes

2024-09-22 19:51 UTC, merged