KS-4-4 Print day training plan
Alex43063/kotlinSprint pull request #21
Opened 2024-09-21 12:54 UTC by Alex43063

2024-09-21 19:26 UTC, ievetrovdev requested changes

2024-09-21 19:26 UTC, ievetrovdev commented on src/main/kotlin/Lesson4-4.kt
> +    val isEvenTrainingDay = if ((numTrainingDay % 2) == 0) {
Верный ход, но давай оптимизируем, в данном случае данное выражение возвращает boolean, блок if здесь не нужен)

2024-09-22 06:45 UTC, Alex43063 commented on src/main/kotlin/Lesson4-4.kt
> +    val isEvenTrainingDay = if ((numTrainingDay % 2) == 0) {
исправил

2024-09-22 18:57 UTC, ievetrovdev approved these changes

2024-09-22 19:52 UTC, merged