KS-4-5 Calculate opportunity for starting ship
Alex43063/kotlinSprint pull request #22
Opened 2024-09-21 13:35 UTC by Alex43063

2024-09-21 19:30 UTC, ievetrovdev requested changes

2024-09-21 19:30 UTC, ievetrovdev commented on src/main/kotlin/Lesson4-5.kt
> +                ((isBroken) && (numOfSeamen in GOOD_CONDITION_SEAMAN_MIN..GOOD_CONDITION_SEAMAN_MAX)
Для длинных условий, которые не помещаются в одну строку, лучше сделать перенос строки после оператора || или &&
Официальная документация [Kotlin Coding Conventions](https://kotlinlang.org/docs/coding-conventions.html) не дает строгих указаний на тему переноса строк внутри условий. Но такой формат я встречал чаще

2024-09-21 19:30 UTC, ievetrovdev commented on src/main/kotlin/Lesson4-5.kt
> +    println("Count of seamen")
Рекомендую отделять пустой строкой каждый запрос для улучшения читабельности кода

2024-09-22 06:52 UTC, Alex43063 commented on src/main/kotlin/Lesson4-5.kt
> +                ((isBroken) && (numOfSeamen in GOOD_CONDITION_SEAMAN_MIN..GOOD_CONDITION_SEAMAN_MAX)
исправил

2024-09-22 06:54 UTC, Alex43063 commented on src/main/kotlin/Lesson4-5.kt
> +    println("Count of seamen")
Добавил пустую строку

2024-09-22 18:57 UTC, ievetrovdev approved these changes

2024-09-22 19:52 UTC, merged