KS1-5 Convert seconds to format hh:mm:ss
Alex43063/kotlinSprint pull request #6
Opened 2024-09-16 17:53 UTC by Alex43063

2024-09-16 19:25 UTC, ievetrovdev requested changes
Я оставил комментарии для доработки. чтобы правильно залить изменения, надо:
 - переключиться в Идее на нужную ветку
 - внести изменения и сделать коммит в эту ветку (следить чтобы в стейдж не добавились лишние задачи, которые не относятся к данной задаче)
 - отправить ссылку в бот на этот же пулл реквест к соответствующей задаче

2024-09-16 19:25 UTC, ievetrovdev commented on src/main/kotlin/Lesson1-5.kt
> +    val minutesInTime = minutes / 60
Все окей, но чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это магическое число, что тоже не является хорошей практикой.

2024-09-16 19:25 UTC, ievetrovdev commented on src/main/kotlin/Lesson1-5.kt
> +    println("${String.format("%02d", hours)}:${String.format("%02d", minutesInTime)}:${String.format("%02d", secondsInTime)}")
Отлично!) можно даже еще аккуратнее сделать
println("%02d:%02d:%02d".format(hours, minutesInTime, secondsInTime))

2024-09-17 11:24 UTC, Alex43063 commented on src/main/kotlin/Lesson1-5.kt
> +    val minutesInTime = minutes / 60
Исправил

2024-09-17 11:24 UTC, Alex43063 commented on src/main/kotlin/Lesson1-5.kt
> +    println("${String.format("%02d", hours)}:${String.format("%02d", minutesInTime)}:${String.format("%02d", secondsInTime)}")
Спасибо, поменял

2024-09-17 20:55 UTC, ievetrovdev approved these changes
Отлично, аппрув!

Теперь эту ветку можно мержить в мастер. напомню, перед созданием новой ветки надо переключиться в мастер, обновить его (чтобы слитые изменения прилетели в локальный проект) и только тогда бранчиться

2024-09-18 07:03 UTC, merged